version: '3'

services:
  manifest-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL__PASSWORD}
      - MSSQL_PID=${SQL__PID}
    ports:
      - "1401:1433"
    expose:
      - 1433
    networks:
      - manifest-2025

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - manifest-2025

  manifest-rabbitmq:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.notifications
    environment:
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
    depends_on:
      - rabbitmq
      - manifest-sql
      - manifest-api
    networks:
      - manifest-2025
    ports:
      - 7111:80
  
  manifest-api:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=manifest-sql,1433;Database=${SQL__DATABASE};User Id=${SQL__USER};Password=${SQL__PASSWORD};ConnectRetryCount=0;TrustServerCertificate=True;
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - "5130:5130"
    networks:
      - manifest-2025
    depends_on:
      - manifest-sql

networks:
  manifest-2025:
    driver: bridge